### PR TITLE
Llama3.2: fix tokenizer

### LINKED ISSUE #134: Llama tokenizer has issues with emojis
See #133

### PR DESCRIPTION
**Pull request by gwenzek**
Fix #134 , superseed #133

Basically the llama3 tokenizer.json has the following config: 

```
  "model": {
    "type": "BPE",
    "dropout": null,
    "unk_token": null,
    "continuing_subword_prefix": null,
    "end_of_word_suffix": null,
    "fuse_unk": false,
    "byte_fallback": false,
    ...
}
```

this it technically invalid because it says the model has no byte fallback and no unknown token either.
This means that unknown emoji can't be converted to bytes nor to the special unknown token.
This ended up in tokenizer.zig using the value of MAX_INT for the UNK token then panicking for out of bound.

So I've added some logic to recognize that in the case of GPT2 encoded vocab (like llama3) that actually contains individual bytes, we should use the "byte_fallback" algorithm even if disabled.

I've also added a Llama3 "well known" normalizer because HF tokenizers doesn't add a dummy prefix for llama3 tokenizer.

Technically this is still not a correct implementation of llama3 tokenizer because we don't do the regex based splitting they do. But even for quite long snippets I tested it now produces exact same tokens.

### CODE REVIEW

File: zml/tokenizer.zig [hunk 1]
```diff
@@ -920,15 +929,16 @@ pub fn fromHfJson(allocator: std.mem.Allocator, tokenizer_path: []const u8) !Tok
         else => return error.InvalidFormat,
     };
 
+    const model = objectGet(main_object, .object, "model") orelse return error.InvalidFormat;
     // TODO: remove all panics
```
Comment (renerocksai) [inline zml/tokenizer.zig:933]: is this comment still valid, I didn't see panics in the diff context?

**Review by renerocksai — APPROVED** [review]
Nice! Sad we have to account for misleading tokenizer.json, though.

File: zml/tokenizer.zig (hunk 1 above)
Comment (gwenzek) [reply zml/tokenizer.zig]: so I had removed most of the .? but had forgotten some.
I remove the last ones and added a more precise TODO wrt EOS/BOS tokens
